# ═══════════════════════════════════════════════════════════════════════
#  SECRETS — Un secret par namespace
# ═══════════════════════════════════════════════════════════════════════

# ── Namespace ecommerce ────────────────────────────────────────────────
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
  labels: {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD:      {{ .Values.postgresql.password | quote }}
  POSTGRES_USER:          {{ .Values.postgresql.username | quote }}
  POSTGRES_DB:            {{ .Values.postgresql.database | quote }}
  MONGO_ROOT_PASSWORD:    {{ .Values.mongodb.rootPassword | quote }}
  MONGO_ROOT_USERNAME:    {{ .Values.mongodb.rootUsername | quote }}
  REDIS_PASSWORD:         {{ .Values.redis.password | quote }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.grafana.adminPassword | quote }}

# ── Namespace keycloak ─────────────────────────────────────────────────
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: keycloak
  labels: {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  KC_DB_PASSWORD:          {{ .Values.keycloak.db.password | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword | quote }}

# ── Namespace monitoring ───────────────────────────────────────────────
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: monitoring
  labels: {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  GRAFANA_ADMIN_PASSWORD: {{ .Values.grafana.adminPassword | quote }}
